My Project: PedidoBiblioteca Class Reference
PedidoBiblioteca Class Reference
Clase que representa de manera genérica un pedido hecho por la biblioteca.
#include <PedidoBiblioteca.h>
Public Member Functions
PedidoBiblioteca ()
Constructor por defecto de la clase PedidoBiblioteca.
PedidoBiblioteca (unsigned anum)
Constructor parametrizado de la clase PedidoBiblioteca.
PedidoBiblioteca (PedidoBiblioteca &pedbi)
Constructor por copia de la clase PedidoBiblioteca.
bool daTrami ()
Método getter del atributo tramitado.
unsigned daNumero ()
Método getter del atributo num.
float daImporte ()
Método getter del atributo importe.
void insertaPedidoLibro (PedidoUsuario *pedidoUsuario)
Se inserta el pedido de un usuario a un libro en concreto en la estructura de datos.
void cierraPedido ()
Da por concluido el trámite de hacer el pedido.
PedidoUsuario * daPedidoUsuario (unsigned i)
Función necesaria para la clase Biblioteca en búsqueda de pedidos.
PedidoBiblioteca & operator= (PedidoBiblioteca &pedbi)
Operador de asignación de la clase PedidoBiblioteca.
~PedidoBiblioteca ()
Destructor de la clase PedidoBiblioteca.
Private Attributes
Fecha fecha
Queda registrada la fecha del pedido actualizada con la fecha y hora del sistema.
float importe
Importe total de todos los usuarios.
bool tramitado
Booleano a true si el pedido esta tramitado, false en otro caso.
unsigned num
Número de pedido de biblioteca.
lista_sin< PedidoUsuario * > pedido_usu
Registro en la estructura de datos del pedido de un usuario.
Friends
ostream & operator<< (ostream &, PedidoBiblioteca &)
Sobrecarga del operador << (de inserción) que permite entre otras cosas mostrar un PedidoBiblioteca con cout.
Detailed Description
Clase que representa de manera genérica un pedido hecho por la biblioteca.
Definition at line 16 of file PedidoBiblioteca.h.
Constructor & Destructor Documentation
PedidoBiblioteca() [1/3]
PedidoBiblioteca::PedidoBiblioteca ()
Constructor por defecto de la clase PedidoBiblioteca.
Definition at line 11 of file PedidoBiblioteca.cpp.
References importe, num, pedido_usu, and tramitado.
PedidoBiblioteca() [2/3]
PedidoBiblioteca::PedidoBiblioteca (unsigned anum) inline
Constructor parametrizado de la clase PedidoBiblioteca.
Parameters
[in] anum unsigned.
Definition at line 34 of file PedidoBiblioteca.h.
References importe, pedido_usu, and tramitado.
PedidoBiblioteca() [3/3]
PedidoBiblioteca::PedidoBiblioteca (PedidoBiblioteca & pedbi) inline
Constructor por copia de la clase PedidoBiblioteca.
Parameters
[in] pedbi PedidoBiblioteca (dir). Instancia de PedidoBiblioteca que se quiere copiar.
Definition at line 46 of file PedidoBiblioteca.h.
References fecha, importe, num, pedido_usu, and tramitado.
~PedidoBiblioteca()
PedidoBiblioteca::~PedidoBiblioteca () inline
Destructor de la clase PedidoBiblioteca.
Definition at line 105 of file PedidoBiblioteca.h.
References lista_sin< T >::limpia().
Member Function Documentation
cierraPedido()
void PedidoBiblioteca::cierraPedido ()
Da por concluido el trámite de hacer el pedido.
Definition at line 65 of file PedidoBiblioteca.cpp.
References tramitado.
Referenced by Biblioteca::cierraPedidoBiblioteca().
daImporte()
float PedidoBiblioteca::daImporte ()
Método getter del atributo importe.
Returns
importe float. Atributo de la clase.
Definition at line 39 of file PedidoBiblioteca.cpp.
References importe.
Referenced by Biblioteca::buscaPedidosBibliotecaPendientes().
daNumero()
unsigned PedidoBiblioteca::daNumero ()
Método getter del atributo num.
Returns
num unsigned. Atributo de la clase.
Definition at line 31 of file PedidoBiblioteca.cpp.
References num.
Referenced by Biblioteca::cierraPedidoBiblioteca(), and Biblioteca::daListaPedBiblioteca().
daPedidoUsuario()
PedidoUsuario * PedidoBiblioteca::daPedidoUsuario (unsigned i)
Función necesaria para la clase Biblioteca en búsqueda de pedidos.
Parameters
[in] i unsigned. El usuario apuntado por i.
Returns
pedido_usu_lee PedidoUsuario*. El pedido que ha hecho el usuario referenciado por i en la estructura de datos.
Definition at line 48 of file PedidoBiblioteca.cpp.
References lista_sin< T >::lee(), and pedido_usu.
daTrami()
bool PedidoBiblioteca::daTrami ()
Método getter del atributo tramitado.
Returns
tramitado bool. Atributo de la clase.
Definition at line 23 of file PedidoBiblioteca.cpp.
References tramitado.
Referenced by Biblioteca::buscaPedidosBibliotecaPendientes(), and Biblioteca::buscaPedidosBibliotecaTramitados().
insertaPedidoLibro()
void PedidoBiblioteca::insertaPedidoLibro (PedidoUsuario * pedidoUsuario)
Se inserta el pedido de un usuario a un libro en concreto en la estructura de datos.
Parameters
[in] pedidoUsuario.
Definition at line 56 of file PedidoBiblioteca.cpp.
References lista_sin< T >::aumenta(), PedidoUsuario::daPrecio(), importe, and pedido_usu.
Referenced by Biblioteca::tramitaPedidoUsuario().
operator=()
PedidoBiblioteca& PedidoBiblioteca::operator= (PedidoBiblioteca & pedbi) inline
Operador de asignación de la clase PedidoBiblioteca.
Parameters
pedbi [in] PedidoBiblioteca (ref). PedidoBiblioteca de la que se quiere realizar una copia.
Returns
Instancia copia realizada.
Definition at line 94 of file PedidoBiblioteca.h.
References fecha, importe, pedido_usu, and tramitado.
Friends And Related Function Documentation
operator<<
ostream& operator<< (ostream & co, PedidoBiblioteca & pb) friend
Sobrecarga del operador << (de inserción) que permite entre otras cosas mostrar un PedidoBiblioteca con cout.
Parameters
[in] ostream. El propio flujo de salida (por referencia).
[in] PedidoBiblioteca. El pedido de la biblioteca (por referencia también).
Returns
[out] co. El flujo de salida ostream debidamente sobrecargado.
Definition at line 75 of file PedidoBiblioteca.cpp.
Member Data Documentation
fecha
Fecha PedidoBiblioteca::fecha private
Queda registrada la fecha del pedido actualizada con la fecha y hora del sistema.
Definition at line 17 of file PedidoBiblioteca.h.
Referenced by operator<<(), operator=(), and PedidoBiblioteca().
importe
float PedidoBiblioteca::importe private
Importe total de todos los usuarios.
Definition at line 18 of file PedidoBiblioteca.h.
Referenced by daImporte(), insertaPedidoLibro(), operator<<(), operator=(), and PedidoBiblioteca().
num
unsigned PedidoBiblioteca::num private
Número de pedido de biblioteca.
Definition at line 20 of file PedidoBiblioteca.h.
Referenced by daNumero(), and PedidoBiblioteca().
pedido_usu
lista_sin<PedidoUsuario *> PedidoBiblioteca::pedido_usu private
Registro en la estructura de datos del pedido de un usuario.
Definition at line 21 of file PedidoBiblioteca.h.
Referenced by daPedidoUsuario(), insertaPedidoLibro(), operator<<(), operator=(), and PedidoBiblioteca().
tramitado
bool PedidoBiblioteca::tramitado private
Booleano a true si el pedido esta tramitado, false en otro caso.
Definition at line 19 of file PedidoBiblioteca.h.
Referenced by cierraPedido(), daTrami(), operator<<(), operator=(), and PedidoBiblioteca().
The documentation for this class was generated from the following files:
PedidoBiblioteca.h
PedidoBiblioteca.cpp