prac1G5: Fecha Class Reference
Fecha Class Reference
Clase sencilla para representar fechas y horas.
#include <Fecha.h>
Classes
class ErrorFechaIncorrecta
Excepción que representa fechas incorrectas.
Public Member Functions
Fecha ()
Constructor por defecto de la clase Fecha. Crea una fecha con la hora actual.
Fecha (unsigned aDia, unsigned aMes, unsigned aAnio, unsigned aHora=0, unsigned aMin=0)
Constructor parametrizado de la clase Fecha. Crea una fecha concreta. Devuelve una excepción ErrorFechaIncorrecta si la fecha introducida no es correcta.
Fecha (const Fecha &f)
Constructor por copia de la clase Fecha.
void asignarDia (unsigned aDia, unsigned aMes, unsigned aAnio)
Asigna un nuevo día.
void asignarHora (unsigned aHora, unsigned aMin)
Asigna una nueva hora.
unsigned verHora () const
Devuelve la hora.
unsigned verMin () const
Obtener minutos.
unsigned verDia () const
Obtener día.
unsigned verMes () const
Obtener mes.
unsigned verAnio () const
Obtener año.
string cadenaDia () const
Obtener una cadena con el día.
string cadenaHora () const
Obtener una cadena con la hora.
string cadena () const
Obtener una cadena con día y hora.
bool mismoDia (const Fecha &f) const
Indica si las dos fechas tienen el mismo día.
bool operator< (const Fecha &f)
Comparar fechas.
Fecha & operator= (const Fecha &f)
Operador de asignación de la clase Fecha.
void anadirMin (int numMin)
Añadir un número de minutos indicado.
void anadirHoras (int numHoras)
Añadir un número de horas indicado.
void anadirDias (int numDias)
Añadir un número de días indicado.
void anadirMeses (int numMeses)
Añadir un número de meses indicado.
void anadirAnios (int numAnios)
Añadir un número de años indicado.
void comprobarFecha (unsigned aDia, unsigned aMes, unsigned aAnio, unsigned aHora, unsigned aMin) const
Comprobación de la validez de una fecha.
void leerTiempo (const tm &t)
Función auxiliar de conversión desde estructura de tiempo tm de time.h.
void escribirTiempo (tm &t)
Función auxiliar de conversión a estructura de tiempo tm de time.h.
~Fecha ()
Destructor de la clase Fecha.
Private Attributes
unsigned dia
unsigned mes
unsigned anio
unsigned hora
unsigned min
Información de fecha y hora.
Static Private Attributes
static const unsigned diasMes [12] = { 31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 }
Almacena los dias por mes.
Detailed Description
Clase sencilla para representar fechas y horas.
Definition at line 15 of file Fecha.h.
Constructor & Destructor Documentation
Fecha() [1/3]
Fecha::Fecha ()
Constructor por defecto de la clase Fecha. Crea una fecha con la hora actual.
Obtiene la hora actual del sistema.
Decodifica la hora en campos separados.
Definition at line 17 of file Fecha.cpp.
References leerTiempo().
Fecha() [2/3]
Fecha::Fecha (unsigned aDia, unsigned aMes, unsigned aAnio, unsigned aHora = 0, unsigned aMin = 0)
Constructor parametrizado de la clase Fecha. Crea una fecha concreta. Devuelve una excepción ErrorFechaIncorrecta si la fecha introducida no es correcta.
Filtra las fechas incorrectas.
Definition at line 29 of file Fecha.cpp.
References anio, comprobarFecha(), dia, hora, mes, and min.
Fecha() [3/3]
Fecha::Fecha (const Fecha & f) inline
Constructor por copia de la clase Fecha.
Definition at line 29 of file Fecha.h.
~Fecha()
Fecha::~Fecha ()
Destructor de la clase Fecha.
Definition at line 191 of file Fecha.cpp.
Member Function Documentation
anadirAnios()
void Fecha::anadirAnios (int numAnios)
Añadir un número de años indicado.
Parameters
[in] numAnios int. Años que queremos incrementar.
Definition at line 160 of file Fecha.cpp.
References escribirTiempo(), and leerTiempo().
anadirDias()
void Fecha::anadirDias (int numDias)
Añadir un número de días indicado.
Parameters
[in] numDias int. Días que queremos incrementar.
Definition at line 136 of file Fecha.cpp.
References escribirTiempo(), and leerTiempo().
anadirHoras()
void Fecha::anadirHoras (int numHoras)
Añadir un número de horas indicado.
Parameters
[in] numHoras int. Horas que queremos incrementar.
Definition at line 124 of file Fecha.cpp.
References escribirTiempo(), and leerTiempo().
anadirMeses()
void Fecha::anadirMeses (int numMeses)
Añadir un número de meses indicado.
Parameters
[in] numMeses int. Meses que queremos incrementar.
Definition at line 148 of file Fecha.cpp.
References escribirTiempo(), and leerTiempo().
anadirMin()
void Fecha::anadirMin (int numMin)
Añadir un número de minutos indicado.
Parameters
[in] numMin int. Minutos que queremos incrementar.
Definition at line 112 of file Fecha.cpp.
References escribirTiempo(), and leerTiempo().
asignarDia()
void Fecha::asignarDia (unsigned aDia, unsigned aMes, unsigned aAnio)
Asigna un nuevo día.
Parameters
[in] aDia unsigned. Nuevo día.
[in] aMes unsigned. Nuevo mes.
[in] aAnio unsigned. Nuevo año.
Definition at line 44 of file Fecha.cpp.
References anio, comprobarFecha(), dia, hora, mes, and min.
asignarHora()
void Fecha::asignarHora (unsigned aHora, unsigned aMin)
Asigna una nueva hora.
Parameters
[in] aHora unsigned. Nueva hora.
[in] aMin unsigned. Nuevos minutos.
Definition at line 56 of file Fecha.cpp.
References anio, comprobarFecha(), dia, hora, mes, and min.
cadena()
string Fecha::cadena () const inline
Obtener una cadena con día y hora.
Returns
Devuelve un string con toda la información de la clase.
Definition at line 85 of file Fecha.h.
Referenced by operator<<().
cadenaDia()
string Fecha::cadenaDia () const
Obtener una cadena con el día.
Returns
Devuelve la fecha en formato string.
Definition at line 172 of file Fecha.cpp.
References anio, dia, and mes.
cadenaHora()
string Fecha::cadenaHora () const
Obtener una cadena con la hora.
Returns
Devuelve la hora en formato string.
Definition at line 182 of file Fecha.cpp.
References hora, and min.
comprobarFecha()
void Fecha::comprobarFecha (unsigned aDia, unsigned aMes, unsigned aAnio, unsigned aHora, unsigned aMin) const
Comprobación de la validez de una fecha.
Parameters
[in] aDia unsigned. Día de la fecha.
[in] aMes unsigned. Mes de la fecha.
[in] aAnio unsigned. Año de la fecha.
[in] aHora unsigned. Hora de la fecha.
[in] aMin unsigned. Minuto de la fecha.
Definition at line 202 of file Fecha.cpp.
References diasMes.
Referenced by asignarDia(), asignarHora(), and Fecha().
escribirTiempo()
void Fecha::escribirTiempo (tm & t)
Función auxiliar de conversión a estructura de tiempo tm de time.h.
Parameters
[out] t tm (dir).
Definition at line 230 of file Fecha.cpp.
References anio, dia, hora, mes, and min.
Referenced by anadirAnios(), anadirDias(), anadirHoras(), anadirMeses(), and anadirMin().
leerTiempo()
void Fecha::leerTiempo (const tm & t)
Función auxiliar de conversión desde estructura de tiempo tm de time.h.
Parameters
[out] t tm (const, dir).
Definition at line 218 of file Fecha.cpp.
References anio, dia, hora, mes, and min.
Referenced by anadirAnios(), anadirDias(), anadirHoras(), anadirMeses(), anadirMin(), and Fecha().
mismoDia()
bool Fecha::mismoDia (const Fecha & f) const inline
Indica si las dos fechas tienen el mismo día.
Parameters
[in] f Fecha(dir, const). Fecha que queremos comprobar.
Returns
bool. True en el caso de que las dos fechas tengan el mismo día, false en cualquier otro caso.
Definition at line 94 of file Fecha.h.
References anio, dia, and mes.
operator<()
bool Fecha::operator< (const Fecha & f)
Comparar fechas.
Parameters
[in] f Fecha(dir, const).
Returns
bool. True en el caso de que la fecha actual sea menor que la fecha parámetro, false en cualquier otro caso.
Definition at line 67 of file Fecha.cpp.
References anio, dia, hora, mes, and min.
operator=()
Fecha & Fecha::operator= (const Fecha & f)
Operador de asignación de la clase Fecha.
Parameters
[in] f Fecha (const, dir). Fecha que queremos copiar.
Returns
Devuelve una nueva instancia de la clase Fecha con los datos de la Fecha pasada como parámetro.
Definition at line 99 of file Fecha.cpp.
References anio, dia, hora, mes, and min.
verAnio()
unsigned Fecha::verAnio () const inline
Obtener año.
Returns
anio unsigned. Atributo de la clase.
Definition at line 73 of file Fecha.h.
verDia()
unsigned Fecha::verDia () const inline
Obtener día.
Returns
dia unsigned. Atributo de la clase.
Definition at line 57 of file Fecha.h.
verHora()
unsigned Fecha::verHora () const inline
Devuelve la hora.
Returns
hora unsigned. Atributo de la clase.
Definition at line 41 of file Fecha.h.
verMes()
unsigned Fecha::verMes () const inline
Obtener mes.
Returns
mes unsigned. Atributo de la clase.
Definition at line 65 of file Fecha.h.
verMin()
unsigned Fecha::verMin () const inline
Obtener minutos.
Returns
min unsigned. Atributo de la clase.
Definition at line 49 of file Fecha.h.
Member Data Documentation
anio
unsigned Fecha::anio private
Definition at line 16 of file Fecha.h.
Referenced by asignarDia(), asignarHora(), cadenaDia(), escribirTiempo(), Fecha(), leerTiempo(), mismoDia(), operator<(), and operator=().
dia
unsigned Fecha::dia private
Definition at line 16 of file Fecha.h.
Referenced by asignarDia(), asignarHora(), cadenaDia(), escribirTiempo(), Fecha(), leerTiempo(), mismoDia(), operator<(), and operator=().
diasMes
const unsigned Fecha::diasMes = { 31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 } static private
Almacena los dias por mes.
Definition at line 17 of file Fecha.h.
Referenced by comprobarFecha().
hora
unsigned Fecha::hora private
Definition at line 16 of file Fecha.h.
Referenced by asignarDia(), asignarHora(), cadenaHora(), escribirTiempo(), Fecha(), leerTiempo(), operator<(), and operator=().
mes
unsigned Fecha::mes private
Definition at line 16 of file Fecha.h.
Referenced by asignarDia(), asignarHora(), cadenaDia(), escribirTiempo(), Fecha(), leerTiempo(), mismoDia(), operator<(), and operator=().
min
unsigned Fecha::min private
Información de fecha y hora.
Definition at line 16 of file Fecha.h.
Referenced by asignarDia(), asignarHora(), cadenaHora(), escribirTiempo(), Fecha(), leerTiempo(), operator<(), and operator=().
The documentation for this class was generated from the following files:
Fecha.h
Fecha.cpp