prac4G5: Aplication Class Reference
Aplication Class Reference
Clase principal la cual derivará en sus variantes de admin y de usuario.
#include <Aplication.h>
Public Member Functions
Aplication ()
Constructor por defecto de la clase Aplication.
Aplication (const Aplication &apl)
Constructor por copia de la clase Aplication.
void aplicacion_usuario ()
Si no sabes la clave de admin has de entrar como usuario registrandote en el sistema.
void aplicacion_admin ()
Aquí se ha solicitado previamente una clave que, si coincide, da entrada al esquema de admin.
Aplication & operator= (const Aplication &apl)
void mostrarMenu ()
Muestra el menú de interacción de la aplicación del admin por pantalla.
void mostrarListaPedidosPendientes (string alogin, string aclave)
Muestra por pantalla una lista con todos los pedidos pendientes de un usuario determinado.
void mostrarTramitarPedido ()
Permite tramitar un pedido de biblioteca determinado.
void mostrarTramitarPedidosUsuario (string alogin, string aclave)
Tramita un pedido de un usuario determinado.
void mostrarConsultarPedidosUsuario (string alogin, string aclave)
Muestra por pantalla los pedidos pendientes de un usuario determinado.
void mostrarListaPedidosTramitados ()
Muestra por pantalla todos los pedidos de biblioteca que han sido tramitados.
void mostrarListaPedidosPendientesBiblioteca ()
Muestra por pantalla todos los pedidos pendientes de Biblioteca.
void mostrarMenuUsuario ()
Muestra el menú de interacción de la aplicación del usuario por pantalla.
void registro (string alogin, string anombre, string aclave)
Registra un usuario en la biblioteca.
void cambiaClave (string alogin, string aclave, string claven)
Cambia la contraseña de un usuario ofreciendo la anterior que tenia.
void consultaLibro (string atitulo)
Hace la consulta de un libro en concreto.
void hazPedido (string aISBN, string atitulo)
Hace un pedido a la Biblioteca.
virtual ~Aplication ()
Destructor de la clase Aplication.
Private Attributes
Biblioteca bi
Objeto de la clase Biblioteca.
Usuario * usu
Referencia a un usuario en concreto.
lista_sin< Usuario > lusu
Lista de los usuarios registrados en la biblioteca.
Libro li
Objeto de la clase libro.
PedidoBiblioteca * pedBi
Referencia a un pedido específico hecho por la biblioteca.
lista_sin< PedidoBiblioteca * > * pedbi
Lista de todos los libros pedidos en cada solicitud.
lista_sin< PedidoUsuario * > * pedusu
Lista de los pedidos hechos por los usuarios.
lista_sin< Libro * > * libro
Lista de todos los libros pedidos por todos los usuarios.
PedidoBiblioteca * pedbipunt
Lista de los pedidos de la biblioteca no tramitados.
Detailed Description
Clase principal la cual derivará en sus variantes de admin y de usuario.
Definition at line 16 of file Aplication.h.
Constructor & Destructor Documentation
Aplication() [1/2]
Aplication::Aplication ()
Constructor por defecto de la clase Aplication.
Definition at line 14 of file Aplication.cpp.
References libro, pedBi, pedbi, pedbipunt, pedusu, and usu.
Aplication() [2/2]
Aplication::Aplication (const Aplication & apl)
Constructor por copia de la clase Aplication.
Definition at line 27 of file Aplication.cpp.
~Aplication()
virtual Aplication::~Aplication () inline virtual
Destructor de la clase Aplication.
Definition at line 77 of file Aplication.h.
References lista_sin< T >::limpia().
Member Function Documentation
aplicacion_admin()
void Aplication::aplicacion_admin ()
Aquí se ha solicitado previamente una clave que, si coincide, da entrada al esquema de admin.
Precondition
La clave debe ser correcta.
Definition at line 34 of file Aplication.cpp.
References Biblioteca::abrePedidoBiblioteca(), bi, mostrarConsultarPedidosUsuario(), mostrarListaPedidosPendientes(), mostrarListaPedidosPendientesBiblioteca(), mostrarListaPedidosTramitados(), mostrarMenu(), mostrarTramitarPedido(), mostrarTramitarPedidosUsuario(), and pedbipunt.
Referenced by main().
aplicacion_usuario()
void Aplication::aplicacion_usuario ()
Si no sabes la clave de admin has de entrar como usuario registrandote en el sistema.
Precondition
Clave de usuario o posibilidad de registrarte como un nuevo usuario.
Definition at line 266 of file Aplication.cpp.
References bi, cambiaClave(), Biblioteca::cargaLibros(), consultaLibro(), hazPedido(), mostrarMenuUsuario(), registro(), and excepcionesBi::errorApertura::what().
Referenced by main().
cambiaClave()
void Aplication::cambiaClave (string alogin, string aclave, string claven)
Cambia la contraseña de un usuario ofreciendo la anterior que tenia.
Parameters
[in] alogin string. Login del usuario
[in] aclave string. Clave de acceso del usuario
[in] claven string. Clave cambiada por el usuario
Definition at line 345 of file Aplication.cpp.
References bi, Biblioteca::buscaUsuario(), Usuario::cambiarClave(), usu, and excepcionesBi::usuNoEncontrado::what().
Referenced by aplicacion_usuario().
consultaLibro()
void Aplication::consultaLibro (string atitulo)
Hace la consulta de un libro en concreto.
Parameters
[in] atitulo string. Titulo del libro en cuestion.
Definition at line 365 of file Aplication.cpp.
References bi, Biblioteca::consultaLibros(), lista_sin< T >::lee(), libro, lista_sin< T >::tamanio(), excepcionesBi::libroNoencontrado::what(), and ErrorElemento::what().
Referenced by aplicacion_usuario().
hazPedido()
void Aplication::hazPedido (string aISBN, string atitulo)
Hace un pedido a la Biblioteca.
Parameters
[in] aISBN string. Código ISBN identificativo del libro (International Standard Book Number).
[in] atitulo string. Titulo del libro en cuestion.
Definition at line 389 of file Aplication.cpp.
References bi, Biblioteca::consultaLibros(), Biblioteca::creaPedidoUsuario(), lista_sin< T >::lee(), libro, usu, excepcionesBi::libroNoencontrado::what(), and ErrorElemento::what().
Referenced by aplicacion_usuario().
mostrarConsultarPedidosUsuario()
void Aplication::mostrarConsultarPedidosUsuario (string alogin, string aclave)
Muestra por pantalla los pedidos pendientes de un usuario determinado.
Parameters
[in] alogin string. Login del usuario
[in] aclave string. Clave de acceso del usuario
Definition at line 196 of file Aplication.cpp.
References bi, Biblioteca::buscaPedidosUsuarioTramitados(), Biblioteca::buscaUsuario(), lista_sin< T >::lee(), pedusu, usu, excepcionesBi::usuNoEncontrado::what(), and ErrorElemento::what().
Referenced by aplicacion_admin().
mostrarListaPedidosPendientes()
void Aplication::mostrarListaPedidosPendientes (string alogin, string aclave)
Muestra por pantalla una lista con todos los pedidos pendientes de un usuario determinado.
Parameters
[in] alogin string. Login del usuario
[in] aclave string. Clave de acceso del usuario
Definition at line 109 of file Aplication.cpp.
References bi, Biblioteca::buscaPedidosUsuarioPendientes(), Biblioteca::buscaUsuario(), lista_sin< T >::lee(), pedusu, usu, excepcionesBi::usuNoEncontrado::what(), excepcionesBi::pedidoUsuarioNoencontrado::what(), and ErrorElemento::what().
Referenced by aplicacion_admin().
mostrarListaPedidosPendientesBiblioteca()
void Aplication::mostrarListaPedidosPendientesBiblioteca ()
Muestra por pantalla todos los pedidos pendientes de Biblioteca.
Definition at line 244 of file Aplication.cpp.
References bi, Biblioteca::buscaPedidosBibliotecaPendientes(), lista_sin< T >::lee(), pedbi, excepcionesBi::pedidoBibliotecaNoencontrado::what(), and ErrorElemento::what().
Referenced by aplicacion_admin().
mostrarListaPedidosTramitados()
void Aplication::mostrarListaPedidosTramitados ()
Muestra por pantalla todos los pedidos de biblioteca que han sido tramitados.
Definition at line 223 of file Aplication.cpp.
References bi, Biblioteca::buscaPedidosBibliotecaTramitados(), lista_sin< T >::lee(), pedbi, excepcionesBi::pedidoBibliotecaNoencontrado::what(), and ErrorElemento::what().
Referenced by aplicacion_admin().
mostrarMenu()
void Aplication::mostrarMenu ()
Muestra el menú de interacción de la aplicación del admin por pantalla.
Definition at line 92 of file Aplication.cpp.
Referenced by aplicacion_admin().
mostrarMenuUsuario()
void Aplication::mostrarMenuUsuario ()
Muestra el menú de interacción de la aplicación del usuario por pantalla.
Definition at line 308 of file Aplication.cpp.
Referenced by aplicacion_usuario().
mostrarTramitarPedido()
void Aplication::mostrarTramitarPedido ()
Permite tramitar un pedido de biblioteca determinado.
Definition at line 137 of file Aplication.cpp.
References bi, Biblioteca::cierraPedidoBiblioteca(), Biblioteca::daListaPedBiblioteca(), pedBi, and excepcionesBi::pedidoBibliotecaNoencontrado::what().
Referenced by aplicacion_admin().
mostrarTramitarPedidosUsuario()
void Aplication::mostrarTramitarPedidosUsuario (string alogin, string aclave)
Tramita un pedido de un usuario determinado.
Parameters
[in] alogin string. Login del usuario.
[in] aclave string. Clave de acceso del usuario.
Obtengo el pedido biblioteca con el número especificado.
Definition at line 156 of file Aplication.cpp.
References bi, Biblioteca::buscaPedidosUsuarioPendientes(), Biblioteca::buscaUsuario(), Biblioteca::daListaPedBiblioteca(), PedidoUsuario::daPrioridad(), lista_sin< T >::lee(), pedBi, pedusu, Biblioteca::tramitaPedidoUsuario(), usu, excepcionesBi::usuNoEncontrado::what(), excepcionesBi::pedidoBibliotecaNoencontrado::what(), and ErrorElemento::what().
Referenced by aplicacion_admin().
operator=()
Aplication& Aplication::operator= (const Aplication & apl) inline
Definition at line 37 of file Aplication.h.
References bi, li, libro, lusu, pedBi, pedbi, pedbipunt, pedusu, and usu.
registro()
void Aplication::registro (string alogin, string anombre, string aclave)
Registra un usuario en la biblioteca.
Parameters
[in] alogin string. Login del usuario
[in] anombre string. Nombre del usuario
[in] aclave string. Clave de acceso del usuario
Definition at line 323 of file Aplication.cpp.
References bi, and Biblioteca::nuevoUsuario().
Referenced by aplicacion_usuario().
Member Data Documentation
bi
Biblioteca Aplication::bi private
Objeto de la clase Biblioteca.
Definition at line 17 of file Aplication.h.
Referenced by aplicacion_admin(), aplicacion_usuario(), cambiaClave(), consultaLibro(), hazPedido(), mostrarConsultarPedidosUsuario(), mostrarListaPedidosPendientes(), mostrarListaPedidosPendientesBiblioteca(), mostrarListaPedidosTramitados(), mostrarTramitarPedido(), mostrarTramitarPedidosUsuario(), operator=(), and registro().
li
Libro Aplication::li private
Objeto de la clase libro.
Definition at line 20 of file Aplication.h.
Referenced by operator=().
libro
lista_sin<Libro *>* Aplication::libro private
Lista de todos los libros pedidos por todos los usuarios.
Definition at line 24 of file Aplication.h.
Referenced by Aplication(), consultaLibro(), hazPedido(), and operator=().
lusu
lista_sin<Usuario> Aplication::lusu private
Lista de los usuarios registrados en la biblioteca.
Definition at line 19 of file Aplication.h.
Referenced by operator=().
pedBi
PedidoBiblioteca* Aplication::pedBi private
Referencia a un pedido específico hecho por la biblioteca.
Definition at line 21 of file Aplication.h.
Referenced by Aplication(), mostrarTramitarPedido(), mostrarTramitarPedidosUsuario(), and operator=().
pedbi
lista_sin<PedidoBiblioteca *>* Aplication::pedbi private
Lista de todos los libros pedidos en cada solicitud.
Definition at line 22 of file Aplication.h.
Referenced by Aplication(), mostrarListaPedidosPendientesBiblioteca(), mostrarListaPedidosTramitados(), and operator=().
pedbipunt
PedidoBiblioteca* Aplication::pedbipunt private
Lista de los pedidos de la biblioteca no tramitados.
Definition at line 25 of file Aplication.h.
Referenced by aplicacion_admin(), Aplication(), and operator=().
pedusu
lista_sin<PedidoUsuario *>* Aplication::pedusu private
Lista de los pedidos hechos por los usuarios.
Definition at line 23 of file Aplication.h.
Referenced by Aplication(), mostrarConsultarPedidosUsuario(), mostrarListaPedidosPendientes(), mostrarTramitarPedidosUsuario(), and operator=().
usu
Usuario* Aplication::usu private
Referencia a un usuario en concreto.
Definition at line 18 of file Aplication.h.
Referenced by Aplication(), cambiaClave(), hazPedido(), mostrarConsultarPedidosUsuario(), mostrarListaPedidosPendientes(), mostrarTramitarPedidosUsuario(), and operator=().
The documentation for this class was generated from the following files:
Aplication.h
Aplication.cpp