prac4G5: ErrorElemento Class Reference
ErrorElemento Class Reference
Clase que representa error de tipo de elemento referenciado.
#include <lista_sin.h>
Public Member Functions
const char * what () const throw ()
Detailed Description
Clase que representa error de tipo de elemento referenciado.
Definition at line 109 of file lista_sin.h.
Member Function Documentation
what()
const char* ErrorElemento::what () const throw () inline
Definition at line 111 of file lista_sin.h.
Referenced by Aplication::consultaLibro(), Aplication::hazPedido(), Aplication::mostrarConsultarPedidosUsuario(), Aplication::mostrarListaPedidosPendientes(), Aplication::mostrarListaPedidosPendientesBiblioteca(), Aplication::mostrarListaPedidosTramitados(), and Aplication::mostrarTramitarPedidosUsuario().
The documentation for this class was generated from the following file:
lista_sin.h