prac4G5: Biblioteca Class Reference
Biblioteca Class Reference
Clase que representa la información y el funcionamiento de una biblioteca.
#include <Biblioteca.h>
Public Member Functions
Biblioteca ()
Constructor por defecto de la clase Biblioteca.
Biblioteca (const Biblioteca &bib)
Constructor por copia de la clase Biblioteca.
lista_sin< PedidoBiblioteca * > * daLBiblioteca ()
Método getter del atributo pedidoBi de la clase.
bool nuevoUsuario (string login, string nombre, string clave)
Introduce un nuevo Usuario en la biblioteca.
Usuario * buscaUsuario (string login, string clave)
Busca un Usuario en la biblioteca.
void cargaLibros (string fichero)
Devuelve una lista con los libros que contengan el titulo que se le pasa como parametro.
lista_sin< Libro * > * consultaLibros (string titulo)
Devuelve una lista con los libros que contengan el título que se le pasa como parámetro.
PedidoUsuario * creaPedidoUsuario (Usuario *usuario, Libro *libro, int prioridad)
Crea un pedido de Usuario.
PedidoBiblioteca * abrePedidoBiblioteca (unsigned anum)
Crea lista pedido de Biblioteca y devuelve su referencia.
void tramitaPedidoUsuario (PedidoUsuario *pedidoUsuario, PedidoBiblioteca *ped)
Añade un pedido de Usuario a un pedido de Biblioteca, pone pedidoUsuario tramitado.
void cierraPedidoBiblioteca (PedidoBiblioteca *ped, unsigned num)
Cierra un pedido de biblioteca marcándolo como tramitado.
lista_sin< PedidoUsuario * > * buscaPedidosUsuarioPendientes (Usuario *usuario)
Devuelve una lista con las refencias a todos los pedidos de un Usuario pendientes.
lista_sin< PedidoUsuario * > * buscaPedidosUsuarioTramitados (Usuario *usuario)
Devuelve una lista con las referencias a todos los pedidos de un Usuario tramitados.
lista_sin< PedidoBiblioteca * > * buscaPedidosBibliotecaPendientes ()
Devuelve una lista con las referencias a los pedidios de biblioteca pendientes.
lista_sin< PedidoBiblioteca * > * buscaPedidosBibliotecaTramitados ()
Devuelve una lista de las referencias de los pedidos de biblioteca tramitados.
PedidoBiblioteca * daListaPedBiblioteca (unsigned num)
Devuelve la lista del pedido de la biblioteca del número de pedido que se le pasa.
Biblioteca & operator= (const Biblioteca &bib)
~Biblioteca ()
Destructor de la clase Biblioteca.
Private Attributes
lista_sin< Usuario * > usur
Lista donde se almacenan todos los usuarios.
lista_sin< PedidoUsuario * > pedido_usu
Lista donde se almacenan todos los pedidos de los usuarios.
lista_sin< PedidoBiblioteca * > pedidoBi
Lista donde se almacenan todos los pedidos hechos por la biblioteca.
lista_sin< Libro * > libro
Lista donde se almacenan todos los libros que posee la biblioteca.
Usuario * usu
Puntero al último usuario introducido en la biblioteca.
Detailed Description
Clase que representa la información y el funcionamiento de una biblioteca.
Definition at line 80 of file Biblioteca.h.
Constructor & Destructor Documentation
Biblioteca() [1/2]
Biblioteca::Biblioteca () inline
Constructor por defecto de la clase Biblioteca.
Definition at line 93 of file Biblioteca.h.
Biblioteca() [2/2]
Biblioteca::Biblioteca (const Biblioteca & bib)
Constructor por copia de la clase Biblioteca.
Definition at line 35 of file Biblioteca.cpp.
~Biblioteca()
Biblioteca::~Biblioteca () inline
Destructor de la clase Biblioteca.
Definition at line 144 of file Biblioteca.h.
References lista_sin< T >::limpia().
Member Function Documentation
abrePedidoBiblioteca()
PedidoBiblioteca * Biblioteca::abrePedidoBiblioteca (unsigned anum)
Crea lista pedido de Biblioteca y devuelve su referencia.
Precondition
Inicialmente estara vacío a la espera de que se añadan pedidos de Usuario.
Parameters
[in] anum unsigned, refiriéndose al número de pedido.
Returns
La referencia al pedido.
Definition at line 139 of file Biblioteca.cpp.
References lista_sin< T >::aumenta(), and pedidoBi.
Referenced by Aplication::aplicacion_admin().
buscaPedidosBibliotecaPendientes()
lista_sin< PedidoBiblioteca * > * Biblioteca::buscaPedidosBibliotecaPendientes ()
Devuelve una lista con las referencias a los pedidios de biblioteca pendientes.
Returns
Lista de referencias a los pedidos de biblioteca pendientes.
Se buscan los pedidos de biblioteca pendientes y se devuelven en una lista.
Definition at line 217 of file Biblioteca.cpp.
References lista_sin< T >::aumenta(), PedidoBiblioteca::daImporte(), PedidoBiblioteca::daTrami(), lista_sin< T >::lee(), pedidoBi, and lista_sin< T >::tamanio().
Referenced by Aplication::mostrarListaPedidosPendientesBiblioteca().
buscaPedidosBibliotecaTramitados()
lista_sin< PedidoBiblioteca * > * Biblioteca::buscaPedidosBibliotecaTramitados ()
Devuelve una lista de las referencias de los pedidos de biblioteca tramitados.
Returns
Lista de referencias a los pedidos de biblioteca tramitados.
Busca pedidos tramitados de biblioteca y los devuelve en una lista.
Definition at line 240 of file Biblioteca.cpp.
References lista_sin< T >::aumenta(), PedidoBiblioteca::daTrami(), lista_sin< T >::lee(), pedidoBi, and lista_sin< T >::tamanio().
Referenced by Aplication::mostrarListaPedidosTramitados().
buscaPedidosUsuarioPendientes()
lista_sin< PedidoUsuario * > * Biblioteca::buscaPedidosUsuarioPendientes (Usuario * usuario)
Devuelve una lista con las refencias a todos los pedidos de un Usuario pendientes.
Parameters
[in] usuario Usuario(ref). Usuario para el que queremos consultar los pedidos pendientes
Returns
Lista de referencias a los pedidos del Usuario pendientes
Se buscan los pedidos pendientes de ese Usuario y se devuelven en esta lista.
Definition at line 179 of file Biblioteca.cpp.
References lista_sin< T >::aumenta(), Usuario::daLogin(), PedidoUsuario::daTramitado(), PedidoUsuario::daUsuario(), lista_sin< T >::lee(), pedido_usu, lista_sin< T >::tamanio(), and usu.
Referenced by Aplication::mostrarListaPedidosPendientes(), and Aplication::mostrarTramitarPedidosUsuario().
buscaPedidosUsuarioTramitados()
lista_sin< PedidoUsuario * > * Biblioteca::buscaPedidosUsuarioTramitados (Usuario * usuario)
Devuelve una lista con las referencias a todos los pedidos de un Usuario tramitados.
Parameters
[in] usuario Usuario(ref). Usuario para el que queremos consultar los pedidos tramitados.
Returns
Lista de referencias a los pedidos del Usuario tramitados.
Busca pedidos de Usuario tramitados devolviéndolos en una lista.
Definition at line 200 of file Biblioteca.cpp.
References lista_sin< T >::aumenta(), Usuario::daLogin(), PedidoUsuario::daTramitado(), PedidoUsuario::daUsuario(), lista_sin< T >::lee(), pedido_usu, lista_sin< T >::tamanio(), and usu.
Referenced by Aplication::mostrarConsultarPedidosUsuario().
buscaUsuario()
Usuario * Biblioteca::buscaUsuario (string login, string clave)
Busca un Usuario en la biblioteca.
Parameters
[in] login string. Login del Usuario. Login del Usuario que se busca
[in] clave string. Clave del Usuario. Clave del Usuario que se busca
Returns
Devuelve un puntero al Usuario que se busca.
Definition at line 52 of file Biblioteca.cpp.
References Usuario::daClave(), Usuario::daLogin(), lista_sin< T >::lee(), lista_sin< T >::tamanio(), and usur.
Referenced by Aplication::cambiaClave(), Aplication::mostrarConsultarPedidosUsuario(), Aplication::mostrarListaPedidosPendientes(), and Aplication::mostrarTramitarPedidosUsuario().
cargaLibros()
void Biblioteca::cargaLibros (string fichero)
Devuelve una lista con los libros que contengan el titulo que se le pasa como parametro.
Parameters
[in] fichero string. Fichero donde se encuentra almacenada la información de los libros.
Convierte a entero un string.
Convierte a entero un string.
Definition at line 67 of file Biblioteca.cpp.
References lista_sin< T >::aumenta(), and libro.
Referenced by Aplication::aplicacion_usuario().
cierraPedidoBiblioteca()
void Biblioteca::cierraPedidoBiblioteca (PedidoBiblioteca * ped, unsigned num)
Cierra un pedido de biblioteca marcándolo como tramitado.
Parameters
[in] ped PedidoBiblioteca(ref). Pedido de biblioteca que queremos cerrar.
[in] num unsigned, se refiere al número de pedido hecho por la biblioteca.
Definition at line 163 of file Biblioteca.cpp.
References PedidoBiblioteca::cierraPedido(), PedidoBiblioteca::daNumero(), lista_sin< T >::lee(), pedidoBi, and lista_sin< T >::tamanio().
Referenced by Aplication::mostrarTramitarPedido().
consultaLibros()
lista_sin< Libro * > * Biblioteca::consultaLibros (string titulo)
Devuelve una lista con los libros que contengan el título que se le pasa como parámetro.
Parameters
[in] titulo string. Título que deben contener los libros.
Returns
Lista con todos los libros que coinciden con la búsqueda realizada.
Devuelve la posición en la cadena.
Si no se modifica el -1 entonces es que no está.
Definition at line 102 of file Biblioteca.cpp.
References lista_sin< T >::aumenta(), Libro::daTitulo(), lista_sin< T >::lee(), libro, and lista_sin< T >::tamanio().
Referenced by Aplication::consultaLibro(), and Aplication::hazPedido().
creaPedidoUsuario()
PedidoUsuario * Biblioteca::creaPedidoUsuario (Usuario * usuario, Libro * libro, int prioridad)
Crea un pedido de Usuario.
Parameters
[in] usuario Usuario(ref). Usuario que realiza el pedido.
[in] libro Libro(ref). Libro que el Usuario ha pedido.
[in] prioridad int. Prioridad del pedido.
Returns
Devueve un puntero al PedidoUsuario creado.
Definition at line 124 of file Biblioteca.cpp.
References lista_sin< T >::aumenta(), libro, and pedido_usu.
Referenced by Aplication::hazPedido().
daLBiblioteca()
lista_sin< PedidoBiblioteca * > * Biblioteca::daLBiblioteca ()
Método getter del atributo pedidoBi de la clase.
Returns
El atributo pedidoBi de la clase.
Definition at line 42 of file Biblioteca.cpp.
References pedidoBi.
daListaPedBiblioteca()
PedidoBiblioteca * Biblioteca::daListaPedBiblioteca (unsigned num)
Devuelve la lista del pedido de la biblioteca del número de pedido que se le pasa.
Parameters
[in] num unsigned, se refiere al número de pedido hecho por la biblioteca.
Returns
El puntero a la lista del número de pedido que se le ha pasado.
Definition at line 261 of file Biblioteca.cpp.
References PedidoBiblioteca::daNumero(), lista_sin< T >::lee(), pedidoBi, and lista_sin< T >::tamanio().
Referenced by Aplication::mostrarTramitarPedido(), and Aplication::mostrarTramitarPedidosUsuario().
nuevoUsuario()
bool Biblioteca::nuevoUsuario (string login, string nombre, string clave)
Introduce un nuevo Usuario en la biblioteca.
Parameters
[in] login string. Login del usuario. Login del nuevo Usuario.
[in] nombre string. Nombre del Usuario. Nombre del nuevo Usuario.
[in] clave string. Clave del Usuario. Clave del nuevo Usuario.
Returns
bool. True si no se puede introducir el Usuario, false en cualquier otro caso.
Devuelve true si está el Usuario y ya no se puede introducir Usuario por motivos obvios.
Definition at line 14 of file Biblioteca.cpp.
References lista_sin< T >::aumenta(), Usuario::daClave(), lista_sin< T >::lee(), Usuario::rellena(), lista_sin< T >::tamanio(), usu, and usur.
Referenced by Aplication::registro().
operator=()
Biblioteca& Biblioteca::operator= (const Biblioteca & bib) inline
Definition at line 132 of file Biblioteca.h.
References libro, pedido_usu, pedidoBi, usu, and usur.
tramitaPedidoUsuario()
void Biblioteca::tramitaPedidoUsuario (PedidoUsuario * pedidoUsuario, PedidoBiblioteca * ped)
Añade un pedido de Usuario a un pedido de Biblioteca, pone pedidoUsuario tramitado.
Parameters
[in] pedidoUsuario PedidoUsuario(ref). Pedido de Usuario que queremos añadir.
[in] ped PedidoBiblioteca(ref). Pedido de biblioteca donde queremeos incluir el pedido de Usuario.
Definition at line 150 of file Biblioteca.cpp.
References PedidoBiblioteca::insertaPedidoLibro(), and PedidoUsuario::tramitaPedido().
Referenced by Aplication::mostrarTramitarPedidosUsuario().
Member Data Documentation
libro
lista_sin<Libro *> Biblioteca::libro private
Lista donde se almacenan todos los libros que posee la biblioteca.
Definition at line 85 of file Biblioteca.h.
Referenced by cargaLibros(), consultaLibros(), creaPedidoUsuario(), and operator=().
pedido_usu
lista_sin<PedidoUsuario *> Biblioteca::pedido_usu private
Lista donde se almacenan todos los pedidos de los usuarios.
Definition at line 83 of file Biblioteca.h.
Referenced by buscaPedidosUsuarioPendientes(), buscaPedidosUsuarioTramitados(), creaPedidoUsuario(), and operator=().
pedidoBi
lista_sin<PedidoBiblioteca *> Biblioteca::pedidoBi private
Lista donde se almacenan todos los pedidos hechos por la biblioteca.
Definition at line 84 of file Biblioteca.h.
Referenced by abrePedidoBiblioteca(), buscaPedidosBibliotecaPendientes(), buscaPedidosBibliotecaTramitados(), cierraPedidoBiblioteca(), daLBiblioteca(), daListaPedBiblioteca(), and operator=().
usu
Usuario* Biblioteca::usu private
Puntero al último usuario introducido en la biblioteca.
Definition at line 86 of file Biblioteca.h.
Referenced by buscaPedidosUsuarioPendientes(), buscaPedidosUsuarioTramitados(), nuevoUsuario(), and operator=().
usur
lista_sin<Usuario *> Biblioteca::usur private
Lista donde se almacenan todos los usuarios.
Definition at line 82 of file Biblioteca.h.
Referenced by buscaUsuario(), nuevoUsuario(), and operator=().
The documentation for this class was generated from the following files:
Biblioteca.h
Biblioteca.cpp