prac4G5: lista_sin< T > Class Template Reference
lista_sin< T > Class Template Reference
Plantilla genérica de estrucutura de datos Lista enlazada.
#include <lista_sin.h>
Public Member Functions
lista_sin ()
Constructor por defecto de la clase lista_sin.
void aumenta (const T &elem)
Añade un elemento nuevo a la lista_sin.
T lee (unsigned pos) const
Devuelve el objeto que se encuentra en la posición pasada como parámetro.
void modifica (T const &elem, unsigned pos)
Modifica el objeto situado en la posición pasada como parámetro con el objeto pasado como parámetro.
void inserta_dato (const T &dato, unsigned pos)
Inserta el objeto que se pasa como parámetro en una posición determinada de lista_sin.
T elimina_dato (unsigned pos)
Elimina el objeto que se encuentra en la posición pasada como parámetro.
unsigned tamanio () const
Devuelve el tamaño de la lista_sin.
void limpia ()
Elimina todos los elementos almacenados en la lista_sin.
lista_sin & operator= (const lista_sin &list)
Operador de asignación de la clase lista_sin.
lista_sin (const lista_sin &list)
Constructor por copia de la clase lista_sin.
~lista_sin (void)
Destructor de la clase lista_sin.
Private Attributes
nodo< T > * nuevo
Nuevo nodo en la Lista enlazada.
nodo< T > * primero
Primer nodo en la Lista enlazada.
nodo< T > * ultimo
Último nodo en la Lista enlazada.
unsigned numElem
Número de nodos de la Lista enlazada.
Detailed Description
template<class T>
class lista_sin< T >
Plantilla genérica de estrucutura de datos Lista enlazada.
Definition at line 29 of file lista_sin.h.
Constructor & Destructor Documentation
lista_sin() [1/2]
template<class T > lista_sin< T >::lista_sin ()
Constructor por defecto de la clase lista_sin.
Definition at line 117 of file lista_sin.h.
lista_sin() [2/2]
template<class T > lista_sin< T >::lista_sin (const lista_sin< T > & list)
Constructor por copia de la clase lista_sin.
Parameters
[in] list lista_sin (dir). lista_sin que queremos copiar.
Definition at line 125 of file lista_sin.h.
~lista_sin()
template<class T > lista_sin< T >::~lista_sin (void)
Destructor de la clase lista_sin.
Definition at line 269 of file lista_sin.h.
Member Function Documentation
aumenta()
template<class T> void lista_sin< T >::aumenta (const T & elem)
Añade un elemento nuevo a la lista_sin.
Parameters
[in] elem T. Objeto que queremos añadir.
Definition at line 146 of file lista_sin.h.
Referenced by Biblioteca::abrePedidoBiblioteca(), Biblioteca::buscaPedidosBibliotecaPendientes(), Biblioteca::buscaPedidosBibliotecaTramitados(), Biblioteca::buscaPedidosUsuarioPendientes(), Biblioteca::buscaPedidosUsuarioTramitados(), Biblioteca::cargaLibros(), Biblioteca::consultaLibros(), Biblioteca::creaPedidoUsuario(), PedidoBiblioteca::insertaPedidoLibro(), and Biblioteca::nuevoUsuario().
elimina_dato()
template<class T > T lista_sin< T >::elimina_dato (unsigned pos)
Elimina el objeto que se encuentra en la posición pasada como parámetro.
Parameters
[in] pos unsigned. Posición en la que se encuentra el dato que queremos eliminar.
Returns
Devuelve el objeto que hemos eliminado de tipo T.
Definition at line 227 of file lista_sin.h.
inserta_dato()
template<class T> void lista_sin< T >::inserta_dato (const T & dato, unsigned pos)
Inserta el objeto que se pasa como parámetro en una posición determinada de lista_sin.
Parameters
[in] dato T (const,dir). Objeto que queremos introducir en lista_sin.
[in] pos unsigned. Posición en la que queremos introducir el objeto.
Incremento "numElem" porque hay un dato mas en la lista.
Definition at line 203 of file lista_sin.h.
lee()
template<class T > T lista_sin< T >::lee (unsigned pos) const
Devuelve el objeto que se encuentra en la posición pasada como parámetro.
Parameters
[in] pos unsigned. Posición en la que se encuentra el objeto.
Returns
Devuelve el tipo de dato que se encuentra en esa posición.
Definition at line 164 of file lista_sin.h.
Referenced by Biblioteca::buscaPedidosBibliotecaPendientes(), Biblioteca::buscaPedidosBibliotecaTramitados(), Biblioteca::buscaPedidosUsuarioPendientes(), Biblioteca::buscaPedidosUsuarioTramitados(), Biblioteca::buscaUsuario(), Biblioteca::cierraPedidoBiblioteca(), Aplication::consultaLibro(), Biblioteca::consultaLibros(), Biblioteca::daListaPedBiblioteca(), PedidoBiblioteca::daPedidoUsuario(), Aplication::hazPedido(), lista_sin< Usuario >::lista_sin(), Aplication::mostrarConsultarPedidosUsuario(), Aplication::mostrarListaPedidosPendientes(), Aplication::mostrarListaPedidosPendientesBiblioteca(), Aplication::mostrarListaPedidosTramitados(), Aplication::mostrarTramitarPedidosUsuario(), Biblioteca::nuevoUsuario(), and lista_sin< Usuario >::operator=().
limpia()
template<class T > void lista_sin< T >::limpia ()
Elimina todos los elementos almacenados en la lista_sin.
Definition at line 260 of file lista_sin.h.
Referenced by Aplication::~Aplication(), Biblioteca::~Biblioteca(), and PedidoBiblioteca::~PedidoBiblioteca().
modifica()
template<class T> void lista_sin< T >::modifica (T const & elem, unsigned pos)
Modifica el objeto situado en la posición pasada como parámetro con el objeto pasado como parámetro.
Parameters
[in] elem T. Objeto que queremos introducir.
[in] pos unsigned. Posición de la lista_sin en la que queremos introducir el objeto.
Definition at line 185 of file lista_sin.h.
operator=()
template<class T > lista_sin< T > & lista_sin< T >::operator= (const lista_sin< T > & list)
Operador de asignación de la clase lista_sin.
Parameters
[in] list lista_sin (dir). lista_sin que queremos copiar.
Returns
lista_sin copia de la lista_sin pasada como parámetro.
Gracias a "aumenta" se reserva memoria para cada nodo.
Definition at line 136 of file lista_sin.h.
tamanio()
template<class T > unsigned lista_sin< T >::tamanio () const
Devuelve el tamaño de la lista_sin.
Returns
Devuelve el tamaño de la lista_sin representado como un entero sin signo.
Definition at line 255 of file lista_sin.h.
Referenced by Biblioteca::buscaPedidosBibliotecaPendientes(), Biblioteca::buscaPedidosBibliotecaTramitados(), Biblioteca::buscaPedidosUsuarioPendientes(), Biblioteca::buscaPedidosUsuarioTramitados(), Biblioteca::buscaUsuario(), Biblioteca::cierraPedidoBiblioteca(), Aplication::consultaLibro(), Biblioteca::consultaLibros(), Biblioteca::daListaPedBiblioteca(), lista_sin< Usuario >::lista_sin(), Biblioteca::nuevoUsuario(), operator<<(), and lista_sin< Usuario >::operator=().
Member Data Documentation
nuevo
template<class T> nodo<T>* lista_sin< T >::nuevo private
Nuevo nodo en la Lista enlazada.
Definition at line 30 of file lista_sin.h.
numElem
template<class T> unsigned lista_sin< T >::numElem private
Número de nodos de la Lista enlazada.
Definition at line 33 of file lista_sin.h.
Referenced by lista_sin< Usuario >::operator=().
primero
template<class T> nodo<T>* lista_sin< T >::primero private
Primer nodo en la Lista enlazada.
Definition at line 31 of file lista_sin.h.
ultimo
template<class T> nodo<T>* lista_sin< T >::ultimo private
Último nodo en la Lista enlazada.
Definition at line 32 of file lista_sin.h.
The documentation for this class was generated from the following file:
lista_sin.h